### ISSUE TITLE
Unable to load issue contents

### ISSUE THREAD

**Issue by bretthayes** [gitscout/gitscout-feedback#146]
I keep receiving this error message when clicking on issues.

![screen shot 2017-01-30 at 3 28 02 pm](https://cloud.githubusercontent.com/assets/1733936/22440298/dd7d6434-e700-11e6-98d1-7bbb1df5486c.png)

**Comment by michael-lefebvre** [comment]
Hi @bretthayes, can you give me more details, please?

- Does this happen on all issues or just some?
- Are you in a private repository? 
- Do tickets include special characters like non-latin languages?
- Do timeline referred to elements like private commit, etc. ?

Thanks for your feedback.

**Comment by bretthayes** [comment]
@michael-lefebvre 

1. It's inconsistent and happens on most of them, but not all.
2. Yes, I'm in a private repo.
3. No, tickets do not include special characters like non-latin languages.
4. I don't know what you mean by timeline.

**Comment by michael-lefebvre** [comment]
by "timeline" I mean the issue's thread. This includes users comments, repository commits, references to others issues, etc.

it seems that you 're in a pretty uncommon situation. This is pretty hard to give you an answer or support 🙁

Next release will include a "bug report" that will collect App's errors messages. I think it will give us more information on your case.

**Comment by antoinerey** [comment]
I also ran into this just seconds ago, on https://github.com/ReactTraining/react-router/pull/4223

So I went to Github to check what could cause some kind of problem. It appears that #4223 is a PR and not an issue. While searching for #4223 on Github, the PR showed up in the issues list (on the Github website). That can maybe explain how the PR is listed in GitScout. Probably a bug on the Github side ?

**Comment by michael-lefebvre** [comment]
hum... this is surprising because we're supposed to filter PR 🤔 I will add this repo and try to reproduce this.

@bretthayes can you confirm that errors appear on PR only?

**Comment by bretthayes** [comment]
@michael-lefebvre these are definitely issues only, not pull requests. I don't have the same problem as @antoinerey.

**Comment by antoinerey** [comment]
I just get this error again on #144.

```
TypeError: Cannot read property 'get' of undefined
    at _callee$ (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90275:75)
    at tryCatch (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7449:41)
    at GeneratorFunctionPrototype.invoke [as _invoke] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7740:23)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7501:22)
    at step (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90132:203)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90132:384
    at tryCatcher (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37419:24)
    at Promise._settlePromiseFromHandler (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37134:32)
    at Promise._settlePromise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37191:19)
    at Promise._settlePromise0 (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37236:11)
    at Promise._settlePromises (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37315:19)
    at Async._drainQueue (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38007:17)
    at Async._drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38017:11)
    at Async.drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37891:15)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:39063:20)
    at Promise._resolveFromExecutor (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37102:11)
    at new Promise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:36701:15)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90132:100
    at getIssueActivityJson (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90508:18)
    at getIssueActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90517:11)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90051:45
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:63192:19
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:30755:13
    at Container.fetchActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164451:8)
    at Container.componentDidMount (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164349:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23072:26
    at measureLifeCyclePerf (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:22882:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23071:12
    at CallbackQueue.notifyAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15508:23)
    at ReactReconcileTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:26223:27)
    at ReactReconcileTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactReconcileTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16621:21)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactUpdatesFlushTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15224:8)
    at ReactUpdatesFlushTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at Object.flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactDefaultBatchingStrategyTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25805:27)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15274:28)
    at dispatchEvent (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25962:21)
    at HTMLDocument.wrapped (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:60387:30)
```

**Comment by angelofrancisco** [comment]
I'm having this issue as well. Here's my log

`
TypeError: Cannot convert undefined or null to object
    at pushEvent (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90382:23)
    at manageEvents (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90295:117)
    at _callee$ (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90481:14)
    at tryCatch (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7449:41)
    at GeneratorFunctionPrototype.invoke [as _invoke] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7740:23)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7501:22)
    at step (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90132:203)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90132:384
    at tryCatcher (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37419:24)
    at Promise._settlePromiseFromHandler (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37134:32)
    at Promise._settlePromise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37191:19)
    at Promise._settlePromise0 (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37236:11)
    at Promise._settlePromises (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37315:19)
    at Async._drainQueue (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38007:17)
    at Async._drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38017:11)
    at Async.drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37891:15)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:39063:20)
    at Promise._resolveFromExecutor (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37102:11)
    at new Promise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:36701:15)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90132:100
    at getIssueActivityJson (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90508:18)
    at getIssueActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90517:11)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90051:45
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:63192:19
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:30755:13
    at Container.fetchActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164451:8)
    at Container.componentDidMount (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164349:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23072:26
    at measureLifeCyclePerf (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:22882:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23071:12
    at CallbackQueue.notifyAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15508:23)
    at ReactReconcileTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:26223:27)
    at ReactReconcileTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactReconcileTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16621:21)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactUpdatesFlushTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15224:8)
    at ReactUpdatesFlushTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at Object.flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactDefaultBatchingStrategyTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25805:27)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15274:28)
    at dispatchEvent (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25962:21)
    at HTMLDocument.wrapped (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:60387:30)
`

**Comment by michael-lefebvre** [comment]
@bretthayes, @antoinerey and @angelofrancisco, we just published an update that must fix this problem. Let me know if it's ok for you.

**Comment by kernelp4nic** [comment]
Hi @michael-lefebvre, just updated the app but still having the same issue:

![2017-02-09_14-35-24](https://cloud.githubusercontent.com/assets/519481/22795321/0c47730a-eed5-11e6-9dc1-9eb03d803e06.png)

```
TypeError: Cannot convert undefined or null to object
    at pushEvent (file:///Applications/Gitscout.app/Contents/Resource
![2017-02-09_14-35-24](https://cloud.githubusercontent.com/assets/519481/22795309/ff0f3e20-eed4-11e6-852c-809b656074ed.png)
s/app.asar/rendered.js:90395:23)
    at manageEvents (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90308:117)
    at _callee$ (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90494:14)
    at tryCatch (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7449:41)
    at GeneratorFunctionPrototype.invoke [as _invoke] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7740:23)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7501:22)
    at step (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:203)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:384
    at tryCatcher (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37419:24)
    at Promise._settlePromiseFromHandler (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37134:32)
    at Promise._settlePromise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37191:19)
    at Promise._settlePromise0 (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37236:11)
    at Promise._settlePromises (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37315:19)
    at Async._drainQueue (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38007:17)
    at Async._drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38017:11)
    at Async.drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37891:15)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:39063:20)
    at Promise._resolveFromExecutor (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37102:11)
    at new Promise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:36701:15)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:100
    at getIssueActivityJson (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90521:18)
    at getIssueActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90530:11)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90064:45
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:63192:19
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:30755:13
    at Container.fetchActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164473:8)
    at Container.componentDidMount (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164371:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23072:26
    at measureLifeCyclePerf (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:22882:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23071:12
    at CallbackQueue.notifyAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15508:23)
    at ReactReconcileTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:26223:27)
    at ReactReconcileTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactReconcileTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16621:21)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactUpdatesFlushTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15224:8)
    at ReactUpdatesFlushTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at Object.flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactDefaultBatchingStrategyTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25805:27)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15274:28)
    at dispatchEvent (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25962:21)
    at HTMLDocument.wrapped (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:60387:30)
```

**Comment by michael-lefebvre** [comment]
hum, I don't like this 🤔 
thanks for your feedback, I will investigate.

**Comment by michael-lefebvre** [comment]
@kernelp4nic Did you have access before and you don't anymore or is it the first time you load it? I just fixed the problem but I'm looking for the reason.

**Comment by bretthayes** [comment]
@michael-lefebvre I just installed the latest update. I'm still not able to see the contents of any issues. However, I like the new addition of the fancy error window 😉

I've included my log below. Seems like there's a `TypeError`.

I should note that I'm on macOS Sierra `10.12.3`. Seems like it's a slightly different `TypeError` than @kernelp4nic has.

![screen shot 2017-02-09 at 6 29 16 pm](https://cloud.githubusercontent.com/assets/1733936/22807566/ae1b1770-eef5-11e6-91b7-a88e68bf50b4.png)

```txt
TypeError: Cannot read property 'get' of undefined
    at _callee$ (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90288:75)
    at tryCatch (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7449:41)
    at GeneratorFunctionPrototype.invoke [as _invoke] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7740:23)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7501:22)
    at step (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:203)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:384
    at tryCatcher (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37419:24)
    at Promise._settlePromiseFromHandler (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37134:32)
    at Promise._settlePromise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37191:19)
    at Promise._settlePromise0 (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37236:11)
    at Promise._settlePromises (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37315:19)
    at Async._drainQueue (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38007:17)
    at Async._drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38017:11)
    at Async.drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37891:15)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:39063:20)
    at Promise._resolveFromExecutor (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37102:11)
    at new Promise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:36701:15)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:100
    at getIssueActivityJson (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90521:18)
    at getIssueActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90530:11)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90064:45
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:63192:19
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:30755:13
    at Container.fetchActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164473:8)
    at Container.componentDidMount (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164371:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23072:26
    at measureLifeCyclePerf (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:22882:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23071:12
    at CallbackQueue.notifyAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15508:23)
    at ReactReconcileTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:26223:27)
    at ReactReconcileTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactReconcileTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16621:21)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactUpdatesFlushTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15224:8)
    at ReactUpdatesFlushTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at Object.flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactDefaultBatchingStrategyTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25805:27)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15274:28)
    at dispatchEvent (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25962:21)
    at HTMLDocument.wrapped (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:60387:30)
```

**Comment by angelofrancisco** [comment]
Hi, I've installed the problem and no dice as well. Here's my recent error log:

    TypeError: Cannot read property 'get' of undefined
    at _callee$ (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90288:75)
    at tryCatch (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7449:41)
    at GeneratorFunctionPrototype.invoke [as _invoke] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7740:23)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7501:22)
    at step (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:203)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:384
    at tryCatcher (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37419:24)
    at Promise._settlePromiseFromHandler (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37134:32)
    at Promise._settlePromise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37191:19)
    at Promise._settlePromise0 (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37236:11)
    at Promise._settlePromises (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37315:19)
    at Async._drainQueue (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38007:17)
    at Async._drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38017:11)
    at Async.drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37891:15) From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:39063:20)
    at Promise._resolveFromExecutor (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37102:11)
    at new Promise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:36701:15)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:100
    at getIssueActivityJson (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90521:18)
    at getIssueActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90530:11)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90064:45
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:63192:19
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:30755:13
    at Container.fetchActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164473:8)
    at Container.componentDidMount (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164371:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23072:26
    at measureLifeCyclePerf (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:22882:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23071:12
    at CallbackQueue.notifyAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15508:23)
    at ReactReconcileTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:26223:27)
    at ReactReconcileTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactReconcileTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16621:21)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactUpdatesFlushTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15224:8)
    at ReactUpdatesFlushTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at Object.flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactDefaultBatchingStrategyTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25805:27)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15274:28)
    at dispatchEvent (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25962:21)
    at HTMLDocument.wrapped (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:60387:30)

**Comment by kernelp4nic** [comment]
> @kernelp4nic Did you have access before and you don't anymore or is it the first time you load it? I just fixed the problem but I'm looking for the reason.

Some issues load fine, but a lot doesn't. I can not remember if those tickets loaded well before. :(

Also I'm getting the same error @angelofrancisco has:

```
TypeError: Cannot read property 'get' of undefined
    at _callee$ (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90288:75)
    at tryCatch (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7449:41)
    at GeneratorFunctionPrototype.invoke [as _invoke] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7740:23)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:7501:22)
    at step (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:203)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:384
    at tryCatcher (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37419:24)
    at Promise._settlePromiseFromHandler (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37134:32)
    at Promise._settlePromise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37191:19)
    at Promise._settlePromise0 (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37236:11)
    at Promise._settlePromises (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37315:19)
    at Async._drainQueue (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38007:17)
    at Async._drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:38017:11)
    at Async.drainQueues (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37891:15)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:39063:20)
    at Promise._resolveFromExecutor (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:37102:11)
    at new Promise (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:36701:15)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90145:100
    at getIssueActivityJson (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90521:18)
    at getIssueActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90530:11)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:90064:45
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:63192:19
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:30755:13
    at Container.fetchActivity (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164473:8)
    at Container.componentDidMount (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:164371:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23072:26
    at measureLifeCyclePerf (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:22882:13)
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:23071:12
    at CallbackQueue.notifyAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15508:23)
    at ReactReconcileTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:26223:27)
    at ReactReconcileTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactReconcileTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16621:21)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactUpdatesFlushTransaction.close (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15224:8)
    at ReactUpdatesFlushTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at ReactUpdatesFlushTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15266:33)
    at Object.flushBatchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15349:20)
    at ReactDefaultBatchingStrategyTransaction.closeAll (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16687:26)
    at ReactDefaultBatchingStrategyTransaction.perform (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:16634:17)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25805:27)
    at Object.batchedUpdates (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:15274:28)
    at dispatchEvent (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:25962:21)
    at HTMLDocument.wrapped (file:///Applications/Gitscout.app/Contents/Resources/app.asar/rendered.js:60387:30)
```

**Comment by michael-lefebvre** [comment]
@kernelp4nic Can you share public tickets with this error please?

**Comment by thibmaek** [comment]
* All issues for me
* Private repo (probably the issue here I think)
* No special chars
* Probably has some references to private issues

**Comment by kernelp4nic** [comment]
> @kernelp4nic Can you share public tickets with this error please?

Sorry but I see it on private repos only, but I found the trigger, every issue added to a github project board it's broken.

**Comment by michael-lefebvre** [comment]
this must be fixed in v0.6.8 🙂

**Comment by kernelp4nic** [comment]
> this must be fixed in v0.6.8 🙂

It works! Thanks @michael-lefebvre !

**Comment by bretthayes** [comment]
Installed the new update and restarted. It works for me as well. Thanks so much for resolving this issue @michael-lefebvre! 😄

**Comment by angelofrancisco** [comment]
Great, works for me as well!
